#define             ENTERO          1
#define             CADENA          2
#define             ID              3
#define             VAR             4
#define             CONST           5
#define             INT             6
#define             IF              7
#define             ELSE            8
#define             WHILE           9
#define             PRINTF          10
#define             READ            11
#define             DOTCOMMA        12
#define             COMMA           13
#define             PLUSOP          14
#define             MINUSOP         15
#define             MULTOP          16
#define             DIVOP           17
#define             LPAREN          18
#define             RPAREN          19
#define             LBRACE          20
#define             RBRACE          21
#define             QMARK           22
#define             COLON           23
#define             ASIGN           24