#define             ENTERO          1
#define             CADENA          2
#define             ID              3
#define             VAR             4
#define             CONST           5
#define             INT             6
#define             IF              7
#define             ELSE            8
#define             PRINTF          9
#define             READ            10
#define             DOTCOMMA        11
#define             COMMA           12
#define             PLUSOP          13
#define             MINUSOP         14
#define             MULTOP          15
#define             DIVOP           16
#define             LPAREN          17
#define             RPAREN          18
#define             LBRACE          19
#define             RBRACE          20
#define             QMARK           21
#define             COLON           22