#define             ENTERO          1
#define             CADENA          2
#define             ID              3
#define             VAR             4
#define             IF              5
#define             ELSE            6
#define             WHILE           7
#define             PRINTF          8
#define             DOTCOMMA        9
#define             COMMA           10
#define             PLUSOP          11
#define             MINUSOP         12
#define             MULTOP          13
#define             DIVOP           14
#define             LPAREN          15
#define             RPAREN          16
#define             LBRACE          17
#define             RBRACE          18
#define             QMARK           19
#define             COLON           20